# Generated by Django 4.2.29 on 2026-03-27 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Bike Name")),
                ("brand", models.CharField(max_length=100, verbose_name="Brand")),
                ("model_year", models.PositiveIntegerField(verbose_name="Model Year")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("scooter", "Scooter"),
                            ("sport", "Sport Bike"),
                            ("cruiser", "Cruiser"),
                            ("electric", "Electric"),
                            ("mountain", "Mountain / Adventure"),
                        ],
                        default="scooter",
                        max_length=20,
                    ),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("petrol", "Petrol"),
                            ("electric", "Electric"),
                            ("hybrid", "Hybrid"),
                        ],
                        default="petrol",
                        max_length=20,
                    ),
                ),
                (
                    "transmission",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("automatic", "Automatic / CVT"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "engine_cc",
                    models.CharField(
                        blank=True, help_text="e.g., 350cc", max_length=30
                    ),
                ),
                (
                    "mileage",
                    models.CharField(
                        blank=True, help_text="e.g., 45 km/l", max_length=30
                    ),
                ),
                ("color", models.CharField(blank=True, max_length=50)),
                (
                    "top_speed",
                    models.CharField(
                        blank=True, help_text="e.g., 120 km/h", max_length=30
                    ),
                ),
                (
                    "price_per_day",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Price Per Day (INR)",
                    ),
                ),
                (
                    "helmet_deposit",
                    models.DecimalField(
                        decimal_places=2,
                        default=500.0,
                        max_digits=8,
                        verbose_name="Helmet Deposit (INR)",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "features",
                    models.TextField(blank=True, help_text="Comma-separated features"),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="bikes/")),
                ("is_available", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "location",
                    models.CharField(default="Pune, Maharashtra", max_length=200),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Bike",
                "verbose_name_plural": "Bikes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=15)),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("general", "General Inquiry"),
                            ("booking", "Booking Help"),
                            ("complaint", "Complaint"),
                            ("other", "Other"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Contact Message",
                "verbose_name_plural": "Contact Messages",
                "ordering": ["-created_at"],
            },
        ),
    ]
